---
name: deploy-extpipes-cli

on:
    push:
        branches:
            - main

jobs:
    deploy_extpipes:
        name: deploy extpipes-cli
        runs-on: ubuntu-latest
        strategy:
            matrix:
                environment: [bootcampstaging]
                include:
                    - environment: bootcampstaging
                      # CDF cluster, like bluefield or greenfield
                      CDF_CLUSTER: bluefield
                      # CDF Project name
                      CDF_PROJECT: bootcampstaging
                      # Azure AD tenant id
                      IDP_TENANT: b429f458-5124-448f-b1ff-5d8cb1bcfda4


        environment: ${{ matrix.environment}}
        env:
            CDF_HOST: https://${{ matrix.CDF_CLUSTER }}.cognitedata.com/

        steps:
            - uses: actions/checkout@v3
            - uses: cognitedata/inso-extpipes-cli@main
              env:
                  EXTPIPES_IDP_CLIENT_ID: ${{ secrets.CLIENT_ID }}
                  EXTPIPES_IDP_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
                  EXTPIPES_CDF_HOST: ${{ env.CDF_HOST }}
                  EXTPIPES_CDF_PROJECT: ${{ matrix.CDF_PROJECT }}
                  EXTPIPES_IDP_TOKEN_URL: https://login.microsoftonline.com/${{ matrix.IDP_TENANT }}/oauth2/v2.0/token
                  EXTPIPES_IDP_SCOPES: ${{ env.CDF_HOST }}.default

              with:
                  # Path to extpipes cli configuration file
                  config_file: ./config/extpipes/extpipes-cli-config.yml
            # "yes"|"no" deploy with special groups and aad_mappings
            #with_special_groups: "yes"
